/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_.alberthgodoy;

/**
 *
 * @author godoy
 */
public class InicioGUI extends javax.swing.JFrame {

    /**
     * Creates new form InicioGUI
     */
    public InicioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSexo = new javax.swing.ButtonGroup();
        buttonEstadoCivil = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jCombo_TipoPersona = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextF_IDPersona = new javax.swing.JTextField();
        jTextF_NombrePersona1 = new javax.swing.JTextField();
        jFormatT_EdadPersona = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_Femenino = new javax.swing.JRadioButton();
        jRadioButton_Masculino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese los datos del tipo persona: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 190, -1));

        getContentPane().add(jCombo_TipoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 180, -1));

        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 30, -1));

        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 60, -1));
        getContentPane().add(jTextF_IDPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, -1));
        getContentPane().add(jTextF_NombrePersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 140, -1));

        jFormatT_EdadPersona.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormatT_EdadPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormatT_EdadPersonaActionPerformed(evt);
            }
        });
        getContentPane().add(jFormatT_EdadPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 140, 30));

        jLabel5.setText("Nombre: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, -1));

        jLabel6.setText("Edad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 60, -1));

        jRadioButton_Femenino.setText("F");
        getContentPane().add(jRadioButton_Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jRadioButton_Masculino.setText("M");
        getContentPane().add(jRadioButton_Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormatT_EdadPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormatT_EdadPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormatT_EdadPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonEstadoCivil;
    private javax.swing.ButtonGroup buttonSexo;
    private javax.swing.JComboBox<String> jCombo_TipoPersona;
    private javax.swing.JFormattedTextField jFormatT_EdadPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton_Femenino;
    private javax.swing.JRadioButton jRadioButton_Masculino;
    private javax.swing.JTextField jTextF_IDPersona;
    private javax.swing.JTextField jTextF_NombrePersona1;
    // End of variables declaration//GEN-END:variables
}
